import AppKit

struct ClipboardManager {
    static let pasteSessionType = NSPasteboard.PasteboardType("com.VoiceInk.PasteSession")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func setClipboard(_ text: String, transient: Bool = false, sessionID: String? = nil) -> Bool {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard pasteboard.setString(text, forType: .string) else {
            return false
        }

        if let bundleIdentifier = Bundle.main.bundleIdentifier {
            pasteboard.setString(bundleIdentifier, forType: sourceType)
        }

        if transient {
            pasteboard.setData(Data(), forType: transientType)
            pasteboard.setData(Data(), forType: autoGeneratedType)
        }

        if let sessionID, !pasteboard.setString(sessionID, forType: pasteSessionType) {
            return false
        }

        return pasteboard.string(forType: .string) == text
    }

    static func copyToClipboard(_ text: String) -> Bool {
        return setClipboard(text, transient: false)
    }
}
